# Generated by Django 4.1.4 on 2022-12-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
    ]
